### ISSUE TITLE
Error in your documentation

### ISSUE THREAD

**Issue by LukeTowers** [mcharytoniuk/octobercms-headless#1]
> Because of OctoberCMS not clear way to provide composer dependencies with marketplace plugins in some scenarios you might need to add alsofronie/eloquent-uuid directly to your composer.json after installing the plugin by typing in the project root:

What isn't clear about using a plugin's composer.json file? All downloads of this plugin from the marketplace should have that library available in a plugin specific vendor directory.

**Comment by mcharytoniuk** [comment]
@LukeTowers I did some other plugin: https://github.com/newridetech/octobercms-inline-assets and I learned that it's composer.json was ignored (it wasn't downloaded to the plugin directory after downloading it from the marketplace despite the fact that OctoberCMS uses `wikimedia/composer-merge-plugin`, so some dependencies were missing). To mitigate that at this time I started looking and found this community thread: https://octobercms.com/forum/post/composer-packages-for-plugins and it pointed to the GA plugin (https://github.com/rainlab/googleanalytics-plugin). It doesn't have vendor directory in the repo but uses `"type": "october-plugin"` instead (the same here for example: https://github.com/octoberrain/drivers-plugin/blob/master/composer.json ). So I did the same here. On test installation it seems to work. 

In general to be honest I don't think that commiting vendor files to the plugin directory is a good idea because it may generate some conflicts. What if two plugins use different versions of the same vendor library? Composer resolves that, I do not know how OctoberCMS autoloader would behave in that situation. I couldn't find an answer to that, so I left that note in the docs just in case.

I'd be happy to know some sure way to provide plugin dependencies that would also minimise the change of conflicts with other plugin's dependencies as it's somewhat an obstacle and makes me somewhat unconfident on how to do that, adding something to the `composer.json` should always work on the other hand.

**Comment by LukeTowers** [comment]
@mcharytoniuk the way OctoberCMS handles composer packages in plugins is as follows:

1. Plugins are to include a composer.json file defining their dependencies. 
2. If a developer uses composer for their project, then they are to run `composer install` and `composer update` from their project root, thus ensuring that all plugin dependencies play nicely together.
3. If a developer does not use composer, but is downloading plugins from the marketplace the plugins need to come with their dependencies already installed.

The marketplace is optimized for the third item. Developers are to provide their plugins with composer.json files included to the marketplace, and as a part of the build process the marketplace pulls the plugin's dependencies into a plugin specific vendor directory (using the `replace` property of composer files to signal to composer what dependencies are already loaded by the base October instance). The build process then removes the composer.json files from the plugin before packaging the plugin directory up for consumption through the marketplace API.

The reason that the marketplace handles it this way is to support both developers that do use composer and developers that don't. If a developer that didn't use composer tried to use a plugin that required it, they would be unable to do so as they wouldn't have a way to easily include dependencies. Thus the marketplace inlines the dependencies into the plugin's vendor directory.

On the other hand, if a developer that does use composer also uses marketplace plugins in their project then having both a composer.json file and a plugin specific vendor directory present will cause issues for that developer because of the project's use of the wikimedia merge plugin, which in this case would result in dependencies being included twice (one in the project vendor's folder because of the wikimedia merge plugin and one in the plugin's vendor directory). Thus, the marketplace removes the composer.json file to solve that problem.

All of this to say is this: If a developer wants to use composer, then they should be including plugins that use composer in their projects exclusively through composer, and not downloading those plugins from the marketplace instead.

See my Installation section on all of my plugins for more information on the installation options available for installing OctoberCMS plugins: https://github.com/LukeTowers/oc-gnuterrypratchett-plugin#installation

**Comment by mcharytoniuk** [comment]
@LukeTowers thank you for a valuable comment. I think it should be posted somewhere in the OctoberCMS docs. 

So in my case I should leave the composer.json as it is now and just remove the line from documentation?

**Comment by LukeTowers** [comment]
@mcharytoniuk yes, that sounds fine. Where would you recommend putting that information in the documentation for developers to get a solid grasp of how it works? Where would you expect to see it?

**Comment by mcharytoniuk** [comment]
@LukeTowers somewhere in the "Plugins section", under "Marketplace considerations" or something similar: http://octobercms.com/docs/plugin . I was looking there in the beginning actually. :) 

Thanks again for help and valuable input!

**Comment by LukeTowers** [comment]
Added in https://github.com/octobercms/docs/commit/7909f640eafd2fe83210ea583494225ac38a7fd1
